image:
  name: "git.statoil.no:4567/sdp/nrlib/nrlib:1.1.0"

variables:
  GIT_STRATEGY: "fetch"
  HTTP_PROXY:   "http://www-proxy.statoil.no:80"
  HTTPS_PROXY:  "http://www-proxy.statoil.no:80"
  FTP_PROXY:    "http://www-proxy.statoil.no:80"
  NO_PROXY:     "git.statoil.no"
  CODE_DIR:     "$CI_PROJECT_DIR"
  ARTIFACTS:    "$CODE_DIR/artifacts"
  MAKE:         "make --makefile=$CODE_DIR/Makefile"
  RUN:          "/bin/bash -c"

stages:
  - check requirements
  - testing
  - doc-tests  # https://docs.python.org/3/library/doctest.html
  - build
  - deploy

check for vulnerabilities:
  stage: check requirements
  script:
    - 'eval $MAKE safety-check'

check for outdated requirements:
  stage: check requirements
  script:
    - 'eval $MAKE check-requirements'

linting:
  stage: testing
  script:
    - 'eval $MAKE linting'
  allow_failure: true

unit testing:
  stage: testing  # https://github.com/ksator/continuous-integration-with-python
  script:
    - 'eval $MAKE unit-tests'

build NRlib for RMS 10.1.1:
  stage: build
  variables:
    DISTRIBUTION_DIR: nrlib-RMS-10.1.1
    PYTHON: "/prog/roxar/rms/versions/10.1.1/linux-amd64-gcc_4_4-release/bin/python"
  script:
    - 'eval $MAKE build'
  artifacts:
    expire_in: 1 week
    paths:
      - '$DISTRIBUTION_DIR'

build NRlib for SDPsoft:
  stage: build
  script:
    - 'eval $MAKE build'
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts/

deploy release candidate:
  stage: deploy
  script:
    - ""  # TODO
  only:
   - master

deploy develop:
  stage: deploy
  script:
    - "" # TODO
  only:
    - develop
